# Generated by Django 4.0 on 2022-02-16 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_shopuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_url',
            field=models.CharField(blank=True, max_length=128, verbose_name='ссылка страницы в Вконтакте'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 8, 47, 49, 905403, tzinfo=utc)),
        ),
    ]
